---

- hosts: all

  tasks:
    - homebrew:
        name: "{{ item }}"
        state: latest
      ignore_errors: true
      with_items:
        - the_silver_searcher
        # add this lines to ~/.bash_profile
        # if [ -f $(brew --prefix)/etc/bash_completion ]; then
        #   . $(brew --prefix)/etc/bash_completion
        # fi
        - bash-completion
      when: ansible_os_family == 'Darwin'

    - composer:
        global_command: true
        command: require
      ignore_errors: true
      # become: true
      with_items:
        - "squizlabs/php_codesniffer=*"
        - "mkusher/padawan=*"
        - "phpmd/phpmd=*"
      tags:
        - all
        - php

    - pip:
        extra_args: "--user"
        name: '{{ item }}'
        state: latest
      with_items:
        - neovim
        - pylint
        - ansible-lint
        - yamllint
        - bashate
        - sexpdata
        - websocket-client
        - jedi
        - psutil
        - setproctitle
      tags:
        - all

    - gem: name={{ item }} state=latest
      become: true
      ignore_errors: true
      with_items:
        - rake
        - neovim
        - mdl
        - haml-lint
        - neovim
        - sqlint
        - rubocop
        - language_server
        - fastri
        - slim_lint
      tags:
        - all
        - ruby

    - npm: name={{ item }} global=true state=latest
      become: true
      ignore_errors: true
      with_items:
        - prettier
        - typescript
        - typings
        - pug-lint
        - livedown
        - js-yaml
        - stylelint
        - js-beautify
        - jsonlint
        - eslint
        - neovim
        - babel-eslint
        - eslint-plugin-jest
        - eslint-plugin-flowtype
        - eslint-plugin-import
        - eslint-import-resolver-webpack
        - eslint-plugin-markdown
        - eslint-plugin-jsx-a11y
        - eslint-config-airbnb
        - eslint-config-airbnb-base
        - eslint-plugin-react
        - eslint-plugin-babel
        - eslint-plugin-jest
      tags:
        - all
        - eslint

    - copy:
        src: ./files/eslintrc
        dest: ~/.eslintrc
        backup: true
      tags:
        - all
        - eslint
