---
- hosts: all
  vars:
    curdir: "{{ playbook_dir }}"
    link: "{{ curdir }}/link"
    copy: "{{ curdir }}/copy"
    source: "{{ curdir }}/source"
  tasks:
    - name: Copy bashrc file to ~ dir, with setted DOTFILES variable to curent dir
      template:
        src: "{{ copy }}/bashrc"
        dest: ~/.bashrc
        backup: yes

    - name: Link files from link directory to ~
      file:
        src: "{{ item }}"
        dest: "~/.{{ item | basename }}"
        state: link
        force: true
      with_fileglob:
        - "{{ link }}/[!.]*"
