---
- hosts: all
  vars:
    curdir: "{{ playbook_dir }}"
  tasks:
# Config:
    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ curdir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - pip: name=neovim state=latest
      become: yes

    - file:
        path=~/.local/share/nvim/site/autoload
        state=directory
        recurse=Yes

    - get_url:
        force: yes
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Addons:
    - composer:
        global_command: true
        command: require
      ignore_errors: true
      become: yes
      with_items:
        - "squizlabs/php_codesniffer=*"
        - "mkusher/padawan=*"
        - "phpmd/phpmd=*"
      tags:
        - all
        - php

    - pip:
        extra_args: "--user"
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - neovim
        - pylint
        - ansible-lint
        - yamllint
        - bashate
        - sexpdata
        - websocket-client
        - jedi
        - psutil
        - setproctitle
      tags:
        - all

    - gem: name={{ item }} state=latest
      become: true
      ignore_errors: true
      with_items:
        - rake
        - neovim
        - mdl
        - haml-lint
        - neovim
        - sqlint
        - rubocop
        - language_server
        - fastri
        - slim_lint
      tags:
        - all
        - ruby

    - npm: name={{ item }} global=true state=latest
      become: true
      ignore_errors: true
      with_items:
        - prettier
        - typescript
        - typings
        - pug-lint
        - livedown
        - js-yaml
        - stylelint
        - js-beautify
        - jsonlint
        - eslint
        - neovim
        - babel-eslint
        - eslint-plugin-jest
        - eslint-plugin-flowtype
        - eslint-plugin-import
        - eslint-import-resolver-webpack
        - eslint-plugin-markdown
        - eslint-plugin-jsx-a11y
        - eslint-config-airbnb
        - eslint-config-airbnb-base
        - eslint-plugin-react
        - eslint-plugin-babel
        - eslint-plugin-jest
      tags:
        - all
        - eslint
