#!/bin/bash
# Script executed by interactive non-login shels.

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='screen-256color';
fi;

if shopt -q login_shell; then
  export DOTFILES=~/.bash_source
  for file in $DOTFILES/{bash_prompt,exports,aliases,functions,options,path}; do
          [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
  unset file;
  # clear
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# added by travis gem
[ -f /Users/mput/.travis/travis.sh ] && source /Users/mput/.travis/travis.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
