#!/bin/bash
# Script executed by interactive non-login shels.

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='screen-256color';
fi;

if shopt -q login_shell; then
  export DOTFILES=~/.bash_source
  for file in $DOTFILES/{bash_prompt,exports,aliases,functions,options,path}; do
          [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
  unset file;
  # clear
fi
