#!/bin/bash

# ls color and with classfication
if [[  `uname` == 'Darwin' ]]; then
  alias ls='ls -F -G'
else
  alias update-all='sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt autoremove -y && sudo npm update -g && brew update && brew upgrade && brew cleanup'
  alias ls='ls -F --color=auto'
fi
alias la='ls -AlFh'


# Grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# Git
alias g='git'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gp='git push'


# Other
alias ..="cd .."
alias :q="exit"

alias ta="tmux attach"
alias tn="tmux new -s"
alias tmuxkillall="tmux ls | grep : | cut -d. -f1 | awk '{print substr($1, 0, length($1)-1)}' | xargs kill"
