#!/bin/bash

# ls color and with classfication
if [[  `uname` == 'Darwin' ]]; then
  alias ls='ls -F -G'
else
  alias ls='ls -F --color=auto'
fi
alias la='ls -AlFh'


# Grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# Git
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '


# Other
alias ..="cd .."
alias :q="exit"

