#!/bin/bash

# Bash options.
# https://www.gnu.org/software/bash/manual/bashref.html#The-Shopt-Builtin

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Automatically prepend `cd` to directory names.

shopt -s autocd

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Autocorrect typos in path names when using the `cd` command.

shopt -s cdspell

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Check the window size after each command and, if necessary, update
# the values of `LINES` and `COLUMNS`.

shopt -s checkwinsize

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Save all lines of a multiple-line command in the same history entry.

shopt -s cmdhist

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Include filenames beginning with a "." in the filename expansion.

shopt -s dotglob

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use extended pattern matching features.

shopt -s extglob

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Append to the history file rather then overwriting it.

shopt -s histappend

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Do not attempt to search the PATH for possible completions when
# completion is attempted on an empty line.

shopt -s no_empty_cmd_completion


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Match filenames in a case-insensitive fashion when performing
# filename expansion.

shopt -s nocaseglob

# HOMEBREW_PREFIX=$(brew --prefix)
# if type brew &>/dev/null; then
#   if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
#     source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
#     echo "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
#     source "/etc/profile.d/bash_completion.sh"
#   else
#     for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
#       [[ -r "$COMPLETION" ]] && source "$COMPLETION"
#     done
#   fi
# fi
# [[ -r "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"  ]] && . "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"


# [ -s "/usr/local/opt/nvm/nvm.sh"  ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
# [ -s "/usr/local/opt/nvm/etc/bash_completion"  ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# # Enable tab completion for `g` by marking it as an alias for `git`
# if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
# 	complete -o default -o nospace -F _git g;
# fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
# [ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Set VI mode, and make C-l to clear screen.
set -o vi
bind -m vi-insert "\C-l":clear-screen

# Add fazzy search on C-f if available
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

